### ISSUE TITLE
smiles_featurizer;'ValueError: Invalid repeat unit. Periodic bond types are mismatching.' 

### ISSUE THREAD

**Issue by kietbphan** [Ramprasad-Group/polygnn#19]
Hi, 
Im trying to make predictions on 12k+ polymers and ran into a problem with double and triple bonds on the terminator. The smiles_featurizer fails to featurize these bonds and the program ends. The exact error is; "Invalid repeat unit. Periodic bond types are mismatching.". Ive also included a picture of the whole output.

Here are some smiles that make the program fail;
'[*]CCCC(=[*])Cl'
'[*]CC(COS(=O)(=O)c1ccc(C)cc1)=C(C#[*])COS(=O)(=O)c1ccc(C)cc1'
'[*]CC(OS(=O)(=O)c1ccc(C)cc1)=C(C#[*])OS(=O)(=O)c1ccc(C)cc1'
<img width="1083" alt="Screenshot 2023-08-22 at 7 04 46 PM" src="https://github.com/Ramprasad-Group/polygnn/assets/51136238/2a6752e1-fd6b-4e91-a4b2-d475bd158c2d">

**Comment by rishigurnani** [comment]
@kietbphan This is occurring because the bonds to each star must match. For example, the first star in the first SMILES has a single bond, but the second star has a double bond. This is nonsensical, and so the program returns an error.

**Comment by rishigurnani** [comment]
Closing this issue since there has been no response. @kietbphan Feel free to reopen if necessary.
