### ISSUE TITLE
whole data access

### ISSUE THREAD

**Issue by shijiale0609** [Ramprasad-Group/polygnn#21]
how to get the whole data used in this paper

**Comment by rishigurnani** [comment]
@shijiale0609 Thanks for your interest in this repo. The sources of each data are listed in the section titled "Data Set and Preparation" of [the companion paper](https://pubs.acs.org/doi/full/10.1021/acs.chemmater.2c02991). Hope this helps.

**Comment by shijiale0609** [comment]
Is there any possibility that part of the training data (like DFT) can be shared?

**Comment by rishigurnani** [comment]
Sure @shijiale0609! A superset of the DFT data used in the polyGNN paper can be found at [this link](https://khazana.gatech.edu/download/2021_Patterns_Chris/MTL_Khazana.zip) on [Khazana](https://khazana.gatech.edu/).

**Comment by rishigurnani** [comment]
Closing this issue.
