### ISSUE TITLE
About Dataset

### ISSUE THREAD

**Issue by littlepeachs** [Ramprasad-Group/polygnn#23]
Hi, I only find part of the dataset in your paper in Khazana. Can you provide a full dataset use in your article? Thanks!

**Comment by littlepeachs** [comment]
Because I am interested to reproduce the result of this paper.
https://github.com/Ramprasad-Group/polygnn/issues/23#issue-2254900043

**Comment by rishigurnani** [comment]
Hi @littlepeachs thank you for the interest! Please refer to https://github.com/Ramprasad-Group/polygnn/issues/21.

I will mark this issue as closed for now, but please feel free to reopen if I did not sufficiently answer your query.

**Comment by littlepeachs** [comment]
Thank you for your reply! I have already get the dataset in the link you provided. The downstream tasks in your paper is more than 30, but there are only eight properties in the dataset, which makes it difficult to fully reproduce your multi-task learning method. I will be very appreciated if you can reply me and provide the whole dataset which contains all properties as your paper. Thank you!

-----原始邮件-----
发件人:rishigurnani ***@***.***>
发送时间:2024-04-30 10:06:24 (星期二)
收件人: Ramprasad-Group/polygnn ***@***.***>
抄送: liwentao ***@***.***>, Mention ***@***.***>
主题: Re: [Ramprasad-Group/polygnn] About Dataset (Issue #23)






Hi @littlepeachs thank you for the interest! Please refer to #21.

I will mark this issue as closed for now, but please feel free to reopen if I did not sufficiently answer your query.
