### ISSUE TITLE
ModuleNotFoundError: No module named 'distutils.cmd'

### ISSUE THREAD

**Issue by williamschertzer** [Ramprasad-Group/polygnn#25]
Upon setup and running the following command:

`poetry run poe torch-linux_win-cuda102

on tyrion2, the following error message is received:

`ModuleNotFoundError: No module named 'distutils.cmd'`

And distutils cannot be installed on python 3.7 without sudo permission

**Comment by rishigurnani** [comment]
Looks like this is a python error. Did you try `poetry run pip install distutils`?

**Comment by rishigurnani** [comment]
This issue has been fixed.
