### ISSUE TITLE
matrix multiplication errors while training

### ISSUE THREAD

**Issue by jnistane3** [Ramprasad-Group/polygnn#3]
Running into an issue of matrix multiplication while training the model, any ideas on how to solve this?
![image](https://user-images.githubusercontent.com/69808123/229870167-a7db9e2f-85cf-44dd-ac53-9eabe0e01dee.png)

**Comment by rishigurnani** [comment]
Hi @jnistane3, it appears that you are training a single task model, right? For single task models, `selector_dim` should equal 0. `selector_dim` refers to the dimension of the selector vector. For multi-task data, `prepare_train` will, for each row in your data, create a selector vector. Each vector contains one dimension per task. For single task, `prepare_train` creates an empty selector vector, so the dimension is equal to 0. I will add comments to `example.py` and `example2.py` to clarify this. Try `selector_dim = 0` and let me know how it goes.

**Comment by jnistane3** [comment]
Perfect, setting selector_dim to zero solved it for my single-task models. Thanks @rishigurnani!
