### ISSUE TITLE
some questions about the dataset

### ISSUE THREAD

**Issue by Don12138** [Ramprasad-Group/polygnn#6]
in the sample.csv, the values of Egc and Egb seem to be reversed:
sample.csv:
![image](https://user-images.githubusercontent.com/50871777/233266870-b5f5961e-50aa-4528-9e18-774094d45e1f.png)
![image](https://user-images.githubusercontent.com/50871777/233266913-c0066122-bb0f-40e8-a820-2611d6786c59.png)

paper:
![image](https://user-images.githubusercontent.com/50871777/233267046-5ebf81e7-66c8-4531-8bf7-1cf9a602fdd0.png)

https://www.polymergenome.org :
![image](https://user-images.githubusercontent.com/50871777/233267088-c1f7d1b1-013c-4cc1-90e7-3484dbebac55.png)

and by the way, how to get the full dataset? the website https://khazana.gatech.edu/ seems have ssl and nginx 400 mistake, or I should  get some keywords to get the dataset

**Comment by rishigurnani** [comment]
Hi @Don12138, thank you for bringing both issues to my attention. First, let me clear up any confusion. The polyGNN models reported in the [companion paper](https://pubs.acs.org/doi/full/10.1021/acs.chemmater.2c02991) are not the same as the models on [Polymer Genome](http://polymergenome.com/). So, your first question is really a Polymer Genome (PG) question, not a polyGNN question. That being said, I did route your question about PG to the people responsible for maintaining it. And indeed there was a bug! Thank you for finding it. It has been fixed.

Regarding Khazana, I also am having trouble accessing it. I will look into the issue and report back.

**Comment by Don12138** [comment]
> Hi @Don12138, thank you for bringing both issues to my attention. First, let me clear up any confusion. The polyGNN models reported in the [companion paper](https://pubs.acs.org/doi/full/10.1021/acs.chemmater.2c02991) are not the same as the models on [Polymer Genome](http://polymergenome.com/). So, your first question is really a Polymer Genome (PG) question, not a polyGNN question. That being said, I did route your question about PG to the people responsible for maintaining it. And indeed there was a bug! Thank you for finding it. It has been fixed.
> 
> Regarding Khazana, I also am having trouble accessing it. I will look into the issue and report back.

> 

Thank for your response to my previous message !!! I truly appreciate your work in the paper and your assistance!!!
I can browse the website of Khazana by ignoring the ssl mistake, and how do I find the full dataset of this paper? I didn't find your paper in the [Data Repository](https://khazana.gatech.edu/module_search/search.php?m=2) (Is it because this paper is newly published？)  or maybe I made a mistake in my operation? The dataset would greatly benefit my ongoing research. I am excited about the opportunity to further analyze and build upon your work, and I am committed to ensuring appropriate use and proper attribution of the data.

**Comment by rishigurnani** [comment]
I am closing this for now. Feel free to reopen if you need.
