### ISSUE TITLE
ValueError: Found input variables with inconsistent numbers of samples: [293, 874]; trying to tune HP on subset of data 

### ISSUE THREAD

**Issue by kietbphan** [Ramprasad-Group/polygnn#7]
Hi, 
Im trying to tune my model HP using a subset of my data and then train on the whole dataset. I am running into this issue of 'inconsistent numbers of samples:'. 
In the code i changed where it begins to '# split train and val data'; I changed the split to split on the subset (master_data) instead of group data. 
<img width="593" alt="xx" src="https://user-images.githubusercontent.com/51136238/236021927-4f30a804-3b53-431c-b015-094f696f670d.png">

**Comment by kietbphan** [comment]
Fixed by creating a subset DF group_data1, and using it for  'find optimal capacity' and 'do hparams opt' section.

**Comment by rishigurnani** [comment]
Hi @kietbphan, it looks like your error is not from `polygnn` but from `sklearn`. Perhaps it is because `master_data` and `group_train_data.prop` are not of equal length.
